config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  
  resources :posts
  resources :tags
  resources :users

  
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'popular' => 'posts#popular'
  get 'favorite' => 'posts#favorite'
  get '/about' => 'posts#about'

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :taggings,  dependent: :destroy
	has_many :tags, through: :taggings
	belongs_to :user

	has_attached_file :image, styles: { large: "500x500", medium: "350x350>", thumb: "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]


	def tag_list
	  self.tags.collect do |tag|
	    tag.name
	  end.join(", ")
	end

	def tag_list=(tags_string)
	  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
	  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
	  self.tags = new_or_found_tags
	end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :posts, through: :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :posts
	
  validates :first_name, :last_name, :email, :username, presence: { error: "Missing info! Please fill out." }
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
  validates :email, uniqueness: true
  validates :username, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception
  	before_filter :set_tags
	helper_method :current_user 

	# setting current user
	def current_user 
	  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end

	def require_user
		if current_user
		else 
  		redirect_to '/posts'
  		flash.notice = "You are not the admin!"
  		end
	end

	# Setting @tags to be available across entire app
	def set_tags
		@tags = Tag.all.order('name ASC')
	end

	#require admin for certain things in controller
	def require_admin 
	  	if current_user && current_user.admin
	  	else
	  		redirect_to root_path
			flash.notice = "You are not the admin!"
		end
	end    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	include PostsHelper
	before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

	def index
	  @posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 5)
	  @home_page = true
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def show
		@post = Post.find(params[:id])
    	if current_user && @post.user_id = current_user.id
    	else	
    		@post.increment!(:countclicks) #-> saves the record
    	end
	end

	def popular
		@posts = Post.all.order('countclicks DESC').first(5)
		@popular_page = true
	end

	def favorite
		@posts = Post.where('rating is not null').order('rating DESC').first(5)
		@favorite_page = true
	end


	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		@post.countclicks = 0
		@post.save
		redirect_to posts_path
		flash.notice = "The post \"#{@post.title}\" was successfully created."
	end

	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to post_path(@post)
		flash.notice = "The post \"#{@post.title}\" was successfully updated."
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
		flash.notice = "The post \"#{@post.title}\" was successfully deleted."
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
	  	@user = User.find_by_username(params[:session][:username])
		  if @user && @user.authenticate(params[:session][:password])
		    session[:user_id] = @user.id
		    redirect_to root_path
		  else
		    redirect_to '/login'
		    flash.notice = "An error occurred upon login. Try again!"
		  end 
	end

	def destroy 
	  	session[:user_id] = nil 
	  	redirect_to '/posts' 
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
	  	@tag = Tag.find(params[:id])
	  	@posts = @tag.posts.order('created_at DESC').paginate(page: params[:page], per_page: 5)
	end

	def index
		@alltags_page = true
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_admin, only: [:index, :edit, :update]
	before_action :require_user, only: [:show]
	include UsersHelper

  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end
  
  def create 
  	@user = User.new(user_params) 
  	if @user.save 
    	session[:user_id] = @user.id 
    	redirect_to '/' 
  	else 
    	redirect_to '/signup' 
    	flash.notice = "You are missing info!"
  	end 
  end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to users_path
		flash.notice = "The user \"#{@user.username}\" was successfully updated."
	end

	def show
		@user = current_user
		@posts = current_user.posts.order('countclicks DESC')
	end

	def edit
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper

	private
		def post_params
	  		params.require(:post).permit(:title, :body, :url, :embed, :tag_list, :image, :user_id, :youtube_url, :rating, :sourceurl)
		end	

	  	def embed(youtube_url)
		    youtube_id = youtube_url.split("=").last
		    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
		end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	private
	  def user_params
	    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :admin)
	  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Mind & music</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'http://ipadapps4school.com/wp-content/uploads/2014/12/the-light-bulb-349400_640.png' %>
</head>
<body>

<nav class = "nav">
  <ul id="slide-out" class="side-nav">
    <%# if !@home_page%>
    <li><a href="/posts">Home</a><li>
    <%# end %>
    <!-- Setting an array equal to the links I want to have then iterating through tags and creating a link in navbar if the tag name is equal to the strings from array-->
    <% @tags.each do |tag| %>
      <% $types_of_posts = ["books", "articles", "videos", "music"] %>

        <% if $types_of_posts.include?(tag.name) %>
          <li><%= link_to tag.name.capitalize, tag_path(tag), class: 'post_title_link'  %></li>
        <%end%>
    <% end %>

    <!-- link to most popular posts (shows the top 5 most clicked on posts)-->
    <% if !@popular_page%>
      <li><%= link_to "Most Popular", popular_path%></li>
    <% end %>
    <!-- link to my favorite/most interesting posts (shows the top 5 posts by rating, which I create when I make a post)-->
    <% if !@favorite_page%>
      <li><%= link_to "Author's Choice", favorite_path%></li>
    <% end %>
    
    <% if !@alltags_page %>
      <li><%= link_to "All Tags", tags_path%></li>
    <%end%>
    
    <%# if current_user && current_user.admin %>
<!--       <li class><%#= link_to "See Users", users_path%></li>
 -->    <%#end%>
  </ul>
  <a href="#" data-activates="slide-out" class="button-collapse show-on-large" id="hamburger-button"><i class="mdi-navigation-menu"></i></a>
  <span id="logo"><a href="/posts">M & M</a></span>

  <% if current_user && current_user.admin %>
    <span id="newpost"><%= link_to "+ Add Post", new_post_path%></span>  
  <%end%>
  <% if current_user %> 
    <span style = "float: right" id="usernav"><%= link_to "logout", logout_path, method: "delete" %></span>
    <span style = "float: right" id="navdivider"> | </span>
    <span style = "float: right" id="usernav"><%= link_to current_user.username.downcase, user_path(current_user) %></span> 
  <%end%>

</nav>


<%= yield %>

<script>
// Initialize collapse button
// $(document).ready(function(){
//   $('.sideNav').hide());

// });

// Hide sideNav
$('.button-collapse').sideNav('hide');
// Show sideNav
$('.button-collapse').sideNav('show');

$('.button-collapse').sideNav({
    menuWidth: 190, // Default is 240
  });


</script>
<br>
<footer class="page-footer" id = "page-footer-override">
  <div class="container">
    <div class="row">
      <div class="col l8 s12" id = "learnmore-override">
        <h5 class="white-text">About</h5>
        <p class="white-text text-lighten-4">This blog was created in order to highlight the author's interests in data and the future of global business and innovation. To complement and enrich these thoughts, the author provides his readers with a variety of carefully chosen music.</p>
      </div>
      <div class="col l2 offset-l2 s12">
        <h5 class="white-text">Learn More</h5>
        <ul>
          <li><a class="white-text text-lighten-3" id = "footer-links" href="/about">About Me</a></li>
          <li><a class="white-text text-lighten-3" id = "footer-links" target="_blank" href="mailto:mfbeek@gmail.com">Contact Me</a></li>
          <li><a class="white-text text-lighten-3" id = "footer-links" target="_blank" href="https://soundcloud.com/mind-music/likes">Soundcloud</a></li>

        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright" id = "footer-copyright-override">
    <span style = "color: white; padding-left: 10px;"><strong>Mind & Music</strong> © 2015</span>
  </div>
</footer>
</body>
</html>

app/views/posts/edit.html.erb
<div class = "container">
	<h2 style = "text-align:center; margin-right: 2vw;"> Edit Post </h2>
		<%= render 'form'%>
		<br>
  	    <%= link_to "Back", post_path(@post), class: "waves-effect waves-light btn", id: "back-button"%>
  	    <br>
  	    <br>
</div>

app/views/posts/favorite.html.erb
<div class = "all_posts">
<br>
	<div class = "header" >
	<br>
		<h1 style = "color: #A5AAAC; padding-left: 13px; font-weight: bold; background-color: white; padding-top: 5px; margin: auto; border-radius: 4px; width: 60%">Blogger's Favorites</h1>
		<br>
		<br>
	</div>
	<% @posts.each do |post| %>
		<div class = "container">
		<div class = "individual_post">
			<ul id="post">
		    <li class = "title_excerpt">
				<%= link_to post.title, post_path(post), class: 'post-title-link'%>
		    </li>
		    <li class = "title_excerpt" style = "font-size: 1.15vw;">
		    	<%=post.created_at.strftime('%b %d, %Y')%>
	    	</li>
<!-- 		    <li>
		    <br>
	  	  	<%# if !post.youtube_url.nil? && post.youtube_url.length > 0%>
		  	  	<div class="youtube-embed-container">  
							<%#= embed(post.youtube_url) %>
				</div>
		    	<%#elsif post.image.exists?%>
			    	<%#= link_to image_tag(post.image.url), post_path(post)%>
		    	<%#else%>	
			    	<%#= link_to image_tag(post.url, class: "img_index"), post_path(post) %>
		    	<%#end%>
	    	</li> -->
	  	  	<% if !post.youtube_url.nil? && post.youtube_url.length > 0%>
	  	  	<li class = "youtube-li">
	  	  		<br>
		  	  	<div class="youtube-index-embed-container">  
					<%= embed(post.youtube_url) %>
				</div>
			</li>
			<%end%>

		  	<% if post.embed.length > 0 %>
		  	<br>
		    	<li class = "title_excerpt">
					<iframe width="60%" height="126" scrolling="no" frameborder="no" src="<%=post.embed%>"></iframe>
		    	</li>
				<%end%>
				<%if post.body.length > 100%>	    		   
			    <li class = "body_excerpt">
			    	<br>
			    	<%if post.embed.length > 0%>
			    		<strong>Music: </strong>
			    	<%else%>
			    		<strong>Mind: </strong>
		    		<%end%>
						<%= post.body.truncate_words(100)%><%=link_to "see more >>", post_path(post), class: 'post_more_link'%>
			    </li>
			    <%else%>
			    <li class = "small_body_excerpt">
			    	<br>
			    	<%if post.embed.length > 0%>
			    		<strong>Music: </strong>
			    	<%else%>
			    		<strong>Mind: </strong>
		    		<%end%>
			    	<%=post.body%>
			    </li>
		    <%end%>
		    <br>
		    <li class = "title_excerpt" style = "font-size: 1.3vw;">
	    		<% if post.user_id %>
						<%= post.user.first_name.capitalize + ' '%> 
				<%end%>
				<% if post.tags.exists?%>
					on 
					<%= raw post.tags.map(&:id).map { |t| link_to Tag.find(t).name, tag_path(t) }.join(', ') %>
				<%end%>
			<br>
			<%if current_user && current_user.admin %>
			Clicks: <%=post.countclicks %> |
			<%end%>
			Rating: <%=post.rating%>/10
		    </li>
		  </ul>
	  </div>
	  </div>
	  <br>
	<% end %>

</div>

app/views/posts/index.html.erb
<div class = "all_posts">
<p style = "text-align: center;"><%= flash.notice %></p>
<!-- Playing with styling for corner border -->
<!-- <p style = "text-align: center;" class="flash"></p>
<br> -->
	<div class = "header" >
	<br>
		<h1 style = "color: #A5AAAC; padding-left: 13px; font-weight: bold; background-color: white; padding-top: 5px; margin: auto; border-radius: 4px; width: 40%">Mind & Music</h1>
	<!-- 	<h1 style = "font-size: .6vw; font-weight: bold; color: #A5AAAC; margin: auto; border-radius: 4px; width: 35%">O O O O O</h1> -->
		<br>
<!-- 		<h4 style = "font-size: 1.4vw; color: #A5AAAC; padding-left: 115px; padding-top: 5px; margin: auto; border-radius: 4px; width: 50%">Stimulate your mind, please your ears.</h4> -->
		<br>
	</div>	
	<% @posts.each do |post| %>
		<div class = "container">
		<div class = "individual_post">
			<ul id="post">
		    <li class = "title_excerpt">
				<%= link_to post.title, post_path(post), class: 'post-title-link'%>
		    </li>
		    <li class = "title_excerpt" style = "color: #A5AAAC; font-size: 1.15vw;">
		    	<%=post.created_at.strftime('%b %d, %Y')%>
	    	</li>
<!-- 		    <li>
		    <br>
	  	  	<%# if !post.youtube_url.nil? && post.youtube_url.length > 0%>
		  	  	<div class="youtube-embed-container">  
							<%#= embed(post.youtube_url) %>
				</div>
		    	<%#elsif post.image.exists?%>
			    	<%#= link_to image_tag(post.image.url), post_path(post)%>
		    	<%#else%>	
			    	<%#= link_to image_tag(post.url, class: "img_index"), post_path(post) %>
		    	<%#end%>
	    	</li> -->
	  	  	<% if !post.youtube_url.nil? && post.youtube_url.length > 0%>
	  	  	<li class = "youtube-li">
	  	  		<br>
		  	  	<div class="youtube-index-embed-container">  
					<%= embed(post.youtube_url) %>
				</div>
			</li>
			<%end%>

		  	<% if post.embed.length > 0 %>
		  	<br>
		    	<li class = "title_excerpt">
					<iframe width="60%" height="126" scrolling="no" frameborder="no" src="<%=post.embed%>"></iframe>
		    	</li>
				<%end%>
				<%if post.body.length > 100%>	    		   
			    <li class = "body_excerpt">
			    	<br>
			    	<%if post.embed.length > 0%>
			    		<strong>Music: </strong>
			    	<%else%>
			    		<strong>Mind: </strong>
		    		<%end%>
						<%= post.body.truncate_words(100)%><%=link_to "see more >>", post_path(post), class: 'post_more_link'%>
			    </li>
			    <%else%>
			    <li class = "small_body_excerpt">
			    	<br>
			    	<%if post.embed.length > 0%>
			    		<strong>Music: </strong>
			    	<%else%>
			    		<strong>Mind: </strong>
		    		<%end%>
			    	<%=post.body%>
			    </li>
		    <%end%>
		    <br>
		    <li class = "title_excerpt" style = "font-size: 1.3vw;">
	    		<% if post.user_id %>
						<%= post.user.first_name.capitalize + ' '%> 
				<%end%>
				<% if post.tags.exists?%>
					on 
					<%= raw post.tags.map(&:id).map { |t| link_to Tag.find(t).name, tag_path(t) }.join(', ') %>
				<%end%>
			<br>
			<%if current_user && current_user.admin %>
			Clicks: <%=post.countclicks %> | Rating: <%=post.rating%>
			<%end%>
		    </li>
		  </ul>
	  </div>
	  </div>
	<% end %>
	<br>
	<span class = "paginate_links"><%= will_paginate @posts %></span>

	<!-- Creating links to dates -->
	<%# array_of_dates = [] %>
		<%# @posts.each do |post| %>
			<%# array_of_dates << post.created_at.strftime('%b %Y')%>
		<%#end%>
	<%# array_of_dates = array_of_dates.uniq{|x| x}%>
	<%# array_of_dates.reverse.each do |date|%>
		<%#= link_to date, root_path%>
	<%#end%>	
	<!-- link to most popular posts -->
</div>

app/views/posts/popular.html.erb
<div class = "all_posts">
<br>
	<div class = "header" >
	<br>
		<h1 style = "color: #A5AAAC; padding-left: 13px; font-weight: bold; background-color: white; padding-top: 5px; margin: auto; border-radius: 4px; width: 40%">Most Popular</h1>
		<br>
		<br>
	</div>		
	<% @posts.each do |post| %>
		<div class = "container">
		<div class = "individual_post">
			<ul id="post">
		    <li class = "title_excerpt">
				<%= link_to post.title, post_path(post), class: 'post-title-link'%>
		    </li>
		    <li class = "title_excerpt" style = "font-size: 1.15vw;">
		    	<%=post.created_at.strftime('%b %d, %Y')%>
	    	</li>
<!-- 		    <li>
		    <br>
	  	  	<%# if !post.youtube_url.nil? && post.youtube_url.length > 0%>
		  	  	<div class="youtube-embed-container">  
							<%#= embed(post.youtube_url) %>
				</div>
		    	<%#elsif post.image.exists?%>
			    	<%#= link_to image_tag(post.image.url), post_path(post)%>
		    	<%#else%>	
			    	<%#= link_to image_tag(post.url, class: "img_index"), post_path(post) %>
		    	<%#end%>
	    	</li> -->
	  	  	<% if !post.youtube_url.nil? && post.youtube_url.length > 0%>
	  	  	<li class = "youtube-li">
	  	  		<br>
		  	  	<div class="youtube-index-embed-container">  
					<%= embed(post.youtube_url) %>
				</div>
			</li>
			<%end%>

		  	<% if post.embed.length > 0 %>
		  	<br>
		    	<li class = "title_excerpt">
					<iframe width="60%" height="126" scrolling="no" frameborder="no" src="<%=post.embed%>"></iframe>
		    	</li>
				<%end%>
				<%if post.body.length > 100%>	    		   
			    <li class = "body_excerpt">
			    	<br>
			    	<%if post.embed.length > 0%>
			    		<strong>Music: </strong>
			    	<%else%>
			    		<strong>Mind: </strong>
		    		<%end%>
						<%= post.body.truncate_words(100)%><%=link_to "see more >>", post_path(post), class: 'post_more_link'%>
			    </li>
			    <%else%>
			    <li class = "small_body_excerpt">
			    	<br>
			    	<%if post.embed.length > 0%>
			    		<strong>Music: </strong>
			    	<%else%>
			    		<strong>Mind: </strong>
		    		<%end%>
			    	<%=post.body%>
			    </li>
		    <%end%>
		    <br>
		    <li class = "title_excerpt" style = "font-size: 1.3vw;">
	    		<% if post.user_id %>
						<%= post.user.first_name.capitalize + ' '%> 
				<%end%>
				<% if post.tags.exists?%>
					on 
					<%= raw post.tags.map(&:id).map { |t| link_to Tag.find(t).name, tag_path(t) }.join(', ') %>
				<%end%>
			<br>
			<%if current_user && current_user.admin %>
			Clicks: <%=post.countclicks %> | Rating: <%=post.rating%>
			<%end%>
		    </li>
		  </ul>
	  </div>
	  </div>
	  <br>
	<% end %>

</div>

app/views/posts/show.html.erb
<div class = "post_show">
<br>
	<div class = "post_info">
		<br>
		<h1><%= @post.title%></h1>
		<br>
		<p class = "tags_on_show">
		<%=@post.created_at.strftime('%b %d, %Y')%>
			<br>
			<% if @post.tags.exists?%>
					<%= raw @post.tags.map(&:id).map { |t| link_to "#" + Tag.find(t).name, tag_path(t) }.join(', ') %>
			<%end%>
			<br>
		    <% if current_user && current_user.admin %>
		    	<%= link_to "Edit", edit_post_path(@post) %>
				<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Really delete the post?"} %>
			<%end%>
		</p>
			<ul id="show_post">
			<!-- if youtube url exists, show video, if image exists show image, if not then show image through url. Basically there will always be either an image uploaded or a url. If there is an image uploaded, show that one no matter what -->
		    <li>
  	  		<% if !@post.youtube_url.nil? && @post.youtube_url.length > 0%>
	    	  	<div class="youtube-show-embed-container">  
							<%= embed(@post.youtube_url) %>
				</div>
		    	<%elsif @post.image.exists?%>
		    		<%= image_tag @post.image.url(:medium) %>
		    	<%else%>	
		    		<%= image_tag @post.url, class: "img_show"%>
		    	<%end%>
	    	</li>
	    	<!-- Soundcloud embedding -->
	  		<% if @post.embed.length > 0 %>
		    	<li>
			    	<div style = "width: 50%; margin: auto;">
							<iframe width="100%" height="140" scrolling="no" frameborder="no" src="<%=@post.embed%>"></iframe>
						</div>
		    	</li>
				<%end%>
		    <li class = "show_body_excerpt">
				<% if @post.embed.length > 0 %>
					<h3 style = "font-size: 2.5vw;"><strong>
						Music:	
					</strong></h3>
				<%else%>
					<h3 style = "font-size: 2.5vw;"><strong>
						Mind:
					</strong></h3>
				<%end%>
				<span class = "show_post_body"><%= @post.body %></span>
		    </li>
		  <br>
  	  	  <%= link_to "Back", posts_path, id: "back-button", class: "waves-effect waves-light btn"%>
		  <% if !@post.sourceurl.nil? && @post.sourceurl.length > 0 %>
		  	<%= link_to "View Source", @post.sourceurl, id: "source-button", :target => "_blank", class: "waves-effect waves-light btn"%>
		  <%end%>
		  </ul>
  </div>
  <br>
  <br>
</div>

app/views/tags/index.html.erb
<div class = "all_posts">
<br>
	<div class = "header" >
	<br>
		<h1 style = "color: #A5AAAC; padding-left: 13px; font-weight: bold; background-color: white; padding-top: 5px; margin: auto; border-radius: 4px; width: 40%">All Tags</h1>
		<br>
		<br>
	</div>	
	<div class = "container" id = "tags-list">
	  <% @tags.each do |tag| %>
		<% tag_frequency = tag.taggings.count %>
	    
	    <% if !$types_of_posts.include?(tag.name) %>
			<% case tag_frequency%>
				<%when 1..2%>
					<%= link_to tag.name.capitalize, tag_path(tag), class: 'small_tag'  %>
				<%when 3..5%>
					<%= link_to tag.name.capitalize, tag_path(tag), class: 'medium_tag'  %>
				<%when 5..1000%>
					<%= link_to tag.name.capitalize, tag_path(tag), class: 'large_tag'  %>
			<% end %>
			&nbsp;
		<%end%>
			
	  <% end %>
	</div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/users/edit.html.erb
<h1>Edit User <%=@user.username%></h1>
<%= render partial: 'users/form' %>
<%= link_to "Back", user_path(@user)%>

app/views/users/show.html.erb
<div class = "container">
<h1 style = "text-align: center;"><%= @user.first_name.capitalize + " " + @user.last_name.capitalize %></h1>
	<ul id = "user-info">
		<li><strong>Username:</strong> <%= @user.username%></li>
		<li><strong>Email:</strong> <%= @user.email%></li>
		<li><strong>First Name:</strong> <%= @user.first_name%></li>
		<li><strong>Last Name:</strong> <%= @user.last_name%></li>
		<li>
		<strong>Admin:</strong> <% if @user.admin%>
		Yes
		<%else%>No
		<%end%>
		</li>
		<%= link_to "Edit", edit_user_path(@user)%>
		<br>
	</ul>
	<h4 style = "color:black">Your Posts:</h4>
	<table class="click-table">
	  <tr>
	    <td style = "font-size: 1.5vw;"><strong>Post Title</strong></td>
	    <td style = "font-size: 1.5vw; text-align: center"><strong>Views</strong></td>
	    <td style = "font-size: 1.5vw; text-align: center"><strong>Type</strong></td>	    
	    <td style = "font-size: 1.5vw; text-align: center"><strong>Date Posted</strong></td> 
	    <td style = "font-size: 1.5vw; text-align: center"><strong>Last Updated</strong></td> 
 

	  </tr>
	  <% @posts.each do |post| %>
	  <tr>
	    <td><%= link_to post.title.capitalize, post_path(post)%></td>
	    <td style = "text-align: center"><%=post.countclicks%></td>
	    <% if post.embed.length > 0 %>
	    	<td style = "width: 15%; text-align: center">Music</td>
    	<% else %>
	    	<td style = "width: 15%; text-align: center">Mind</td>
	    <%end%>   	
	    <td style = "text-align: center"><%=post.created_at.strftime('%b %d, %Y')%></td> 	    
	    <td style = "text-align: center"><%=post.updated_at.strftime('%b %d, %Y')%></td> 	    
 

	  </tr>
	  <%end%>
	</table>
	<ul id = "user-info">
		<%= link_to "See Users", users_path%>
		<br>
	</ul>
</div>